version: '3.8'

services:
  api:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:80"

  db_updater:
    build: .
    container_name: db_updater_container
    command: ["python", "src/database_helper.py", "--type", "update", "--pathtodb", "data"]
    restart: unless-stopped

volumes:
  database: